stages:
  raw_dataset_creation:
    cmd: python src/data/load_data.py --config=params.yaml
    deps:
    - src/data/load_data.py
    - data/external/train.csv
    outs:
    - data/raw/train.csv
  
  great_expectation_validation:
    cmd: python src/data/data_validation.py --config=params.yaml
    deps:
    - src/data/data_validation.py
    - data/raw/train.csv
    - data/raw/train_new.csv
    outs:
    - great_expectations/exp_json_file.json
  
  split_data:
    cmd: python src/data/split_data.py --config=params.yaml
    deps:
    - src/data/split_data.py
    - data/raw/train.csv
    outs:
    - data/processed/churn_train.csv
    - data/processed/churn_test.csv

  model_train:
    cmd: python src/models/train_model.py --config=params.yaml
    deps:
    - data/processed/churn_train.csv
    - data/processed/churn_test.csv
    - src/models/train_model.py
    params:
    - random_forest.max_depth
    - random_forest.n_estimators

  log_production_model:
    cmd: python src/models/production_model_selection.py --config=params.yaml
    deps:
    - src/models/production_model_selection.py
    params:
    - random_forest.max_depth
    - random_forest.n_estimators
    outs:
    - models/model.joblib
  
  Monitor_Dashboard:
    cmd: python src/models/model_monitor.py --config=params.yaml
    deps:
    - src/models/model_monitor.py
    - data/raw/train_new.csv
    outs:
    - reports/data_and_target_drift_dashboard.html

  wand_model_track:
    cmd: python src/models/train_model_track_WNB.py --config=params.yaml
    deps:
    - data/processed/churn_train.csv
    - data/processed/churn_test.csv
    - src/models/train_model_track_WNB.py
    outs:
    - wandb