wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.7
    start_time: 1637630185
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 13
      4: 3.8.7
      5: 0.12.6
      8:
      - 3
      - 5
    viz:
      class_proportions:
        historyFieldSettings:
          key: class_proportions
          x-axis: _step
        id: wandb/class_proportions/v1
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
      learning_curve:
        historyFieldSettings:
          key: learning_curve
          x-axis: _step
        id: wandb/learning_curve/v1
      precision_recall:
        historyFieldSettings:
          key: precision_recall
          x-axis: _step
        id: wandb/pr_curve/v1
      roc:
        historyFieldSettings:
          key: roc
          x-axis: _step
        id: wandb/roc/v1
