wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.7
    start_time: 1637288795
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 13
      4: 3.8.7
      5: 0.12.6
      8:
      - 3
      - 5
    viz:
      feature_importances:
        historyFieldSettings:
          key: feature_importances
          x-axis: _step
        id: wandb/feature_importances/v1
      learning_curve:
        historyFieldSettings:
          key: learning_curve
          x-axis: _step
        id: wandb/learning_curve/v1
